name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Pip, Twine and Wheel
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install twine
          pip install wheel

      - name: Build
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*

      - name: Publish package to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
